---
- name: Set default policies
  ansible.builtin.iptables:
    chain: "{{ item.chain }}"
    policy: "{{ item.policy }}"
  with_items:
    - { chain: 'INPUT', policy: '{{ firewall_default_input_policy }}' }
    - { chain: 'FORWARD', policy: '{{ firewall_default_forward_policy }}' }
    - { chain: 'OUTPUT', policy: '{{ firewall_default_output_policy }}' }

- name: Allow established connections
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Allow loopback interface
  ansible.builtin.iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT

- name: Configure allowed TCP ports
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item }}"
    jump: ACCEPT
  with_items: "{{ firewall_allowed_tcp_ports }}"

- name: Configure allowed UDP ports
  ansible.builtin.iptables:
    chain: INPUT
    protocol: udp
    destination_port: "{{ item }}"
    jump: ACCEPT
  with_items: "{{ firewall_allowed_udp_ports }}"

- name: Add custom rules
  ansible.builtin.iptables:
    chain: INPUT
    protocol: "{{ item.protocol }}"
    source: "{{ item.source | default(omit) }}"
    destination_port: "{{ item.port }}"
    jump: ACCEPT
  with_items: "{{ firewall_custom_rules }}"

- name: Configure logging for dropped packets
  ansible.builtin.iptables:
    chain: INPUT
    jump: LOG
    log_prefix: "[IPTABLES DROP] "
  when: firewall_enable_logging | bool
